SELECT CONCAT(CONCAT(A.SCAB, A.SCAN), A.SCAS) AS ACCOUNT_IDENTIFIER,
       B.NEEAN AS EXTERNAL_ACCOUNT_NUMBER_TEXT,
       A.SCAN AS CUSTOMER_IDENTIFIER,
       A.SCAS AS ACCOUNT_SUFFIX_TEXT,
       A.SCSHN AS ACCOUNT_CUSTOMER_NAME,
       A.SCAB AS ACCOUNT_BRANCH_CODE,
       A.SCACT AS ACCOUNT_TYPE_CODE,
       E.C5ATD AS ACCOUNT_TYPE_DESCRIPTION,
       A.SCCTP AS CUSTOMER_SUBTYPE_CODE,
       F.C4CTD AS CUSTOMER_SUBTYPE_DESCRIPTION,
       A.SCCCY AS ORIGINAL_CURRENCY_CODE,
       G.C8CUR AS ORIGINAL_CURRENCY_DESCRIPTION,
       A.SCAI17 AS ACCOUNT_BLOCK_STATUS_FLAG,
       CASE WHEN A.SCAI20='Y' THEN 'N' ELSE 'Y' END AS ACCOUNT_ACTIVE_STATUS_FLAG,
       A.SCAIJ1 AS ACCOUNT_DORMANT_STATUS_FLAG,
       A.SCAI30 AS ACCOUNT_CLOSE_STATUS_FLAG,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCOAD AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS ACCOUNT_OPEN_DATE,
       CASE WHEN A.SCCAD=0 THEN cast(from_unixtime(unix_timestamp(CAST(19000000 AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date)
           ELSE cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCCAD AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date)
       END AS ACCOUNT_CLOSE_DATE,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCDLE AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS LAST_TRANSACTION_DATE,
       A.SCAIJ2 AS ACCOUNT_SEMI_ACTIVE_STATUS_FLAG,
       H.B02002 AS CUSTOMER_PENSION_NUMBER_TEXT,
       H.B02003 AS PAYMENT_OFFICE_TYPE_CODE,
       H.B02004 AS CUSTOMER_PENSION_CODE,
       I.BHDSC AS CUSTOMER_PENSION_DESCRIPTION,
       H.B01024 AS CUSTOMER_PENSION_TYPE_CODE,
       J.BHDSC AS CUSTOMER_PENSION_TYPE_DESCRIPTION,
       A.SCAIC7 AS JOIN_ACCOUNT_FLAG,
       (A.SCBAL+A.SCSUMC+A.SCSUMD)/POWER(10, CAST(G.C8CED AS DOUBLE)) AS OUTSTANDING_BALANCE_AMOUNT,
       A.SCBAL/POWER(10, CAST(G.C8CED AS DOUBLE)) AS LEDGER_BALANCE_AMOUNT,
       A.SCAIC4 AS SYSTEM_GENERATE_POSTING,
       A.SCAI14 AS DECEASE_FLAG,
       A.SCAI46 AS CONTINGET_ACCOUNT_FLAG,
       A.SCAIJ3 AS FSCM_ACCOUNT_FLAG,
       A.SCAIA5 AS INTER_BRANCH_TRANSACTION_FLAG,
       A.SCAIA6 AS DEBIT_ALLOWABLE_FLAG,
       A.SCSUMD/POWER(10, CAST(G.C8CED AS DOUBLE)) AS SHADOW_DEBIT_BALANCE_AMOUNT,
       A.SCSUMC/POWER(10, CAST(G.C8CED AS DOUBLE)) AS SHADOW_CREDIT_BALANCE_AMOUNT,
       A.SCSUMA/POWER(10, CAST(G.C8CED AS DOUBLE)) AS SHADOW_ADJUSTMENT_BALANCE_AMOUNT,
       A.SCRBA/POWER(10, CAST(G.C8CED AS DOUBLE)) AS RESERVE_BALANCE_AMOUNT,
       H.B01027 AS RELATIONSHIP_OFFICER_CODE,
       K.BHDSC AS RELATIONSHIP_OFFICER_DESCRIPTION,
       H.B01028 AS RELATIONSHIP_ANCHOR_CODE,
       L.BHDSC AS RELATIONSHIP_ANCHOR_DESCRIPTION,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCLDTD AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS LAST_DEBIT_DATE,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCLCTD AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS LAST_CREDIT_DATE,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCDLM AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS LAST_MAINTENANCE_DATE,
       A.SCRETP AS RETENTION_MONTH_PERIOD_COUNT,
       A.SCBALS/POWER(10, CAST(G.C8CED AS DOUBLE)) AS LAST_STATEMENT_BALANCE_AMOUNT,
       cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCSTML AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date) AS LAST_STATEMENT_DATE,
       A.SCSFC AS STATEMENT_FREQUENCY_TYPE_CODE,
       A.SCSTNL AS LAST_STATEMENT_NUMBER,
       A.SCAI92 AS NON_DEBET_ACCOUNT_FLAG,
       CASE WHEN C.MDBICO='23' THEN '02' WHEN C.MDBICO='24' THEN '01' ELSE '03' END AS CASA_ACCOUNT_TYPE_CODE,
       'EQ' AS SOURCE_SYSTEM_CODE,
       CURRENT_DATE AS RECORD_LAST_UPDATE_DATE,
       A.SCODL/POWER(10, CAST(G.C8CED AS DOUBLE)) AS OVERDRAFT_LIMIT_AMOUNT,
       CASE WHEN A.SCLED=0 THEN cast(from_unixtime(unix_timestamp(CAST('19000101'AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date)
           ELSE cast(from_unixtime(unix_timestamp(CAST(19000000+A.SCLED AS varchar(10)), 'yyyyMMdd'), 'yyyy-MM-dd') AS date)
       END AS OVERDRAFT_LIMIT_EXPIRY_DATE,
       CONCAT('01', A.SCAN) AS CRN_NUMBER_TEXT
FROM {0}.STAGING_SCPF a
INNER JOIN {0}.STAGING_NEPF b ON a.SCAB=B.NEAB AND A.SCAN=B.NEAN AND A.SCAS=B.NEAS
INNER JOIN {0}.STAGING_YMSTMAP c ON c.MDACTY=A.SCACT AND C.MDFORM='DL' AND C.MDBICO IN ('23', '24', '99')
LEFT JOIN {0}.STAGING_C5PF e ON e.C5ATP=A.SCACT
LEFT JOIN {0}.STAGING_C4PF f ON f.C4CTP=A.SCCTP
LEFT JOIN {0}.STAGING_C8PF g ON g.C8CCY=A.SCCCY
LEFT JOIN {0}.STAGING_B0PF h ON h.B0AB=A.SCAB AND H.B0AN=A.SCAN AND H.B0AS=A.SCAS
LEFT JOIN {0}.STAGING_BHPF i ON i.BHCITM='2004' AND I.BHEQF='AC' AND I.BHCVAL=H.B02004
LEFT JOIN {0}.STAGING_BHPF j ON j.BHCITM='1024' AND J.BHEQF='AC' AND J.BHCVAL=H.B01024
LEFT JOIN {0}.STAGING_BHPF k ON k.BHCITM='1027' AND K.BHEQF='AC' AND K.BHCVAL=H.B01027
LEFT JOIN {0}.STAGING_BHPF l ON l.BHCITM='1028' AND L.BHEQF='AC' AND L.BHCVAL=H.B01028
WHERE 1=1
